package interfaz;

import java.awt.EventQueue;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.BufferedWriter;

import javax.imageio.ImageIO;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import business.Person;
import javax.swing.JButton;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * Clase que sirve para mostrar los diferentes datos de los objetos de la clase Person
 * @author Jaime Serrano Quílez
 * @version Final
 * @date 24-02-2023
 */
public class DisplayJPanel extends javax.swing.JPanel {

	 /**
     * Creates new form DisplayJPanel
     */
    //Person person;
    public DisplayJPanel(Person person) {
        initComponents();
       // this.person=person;
        displayPerson(person);
    }
    
    public void displayPerson(Person person){
        
        nameTextField.setText(person.getNombre());
        emailTextField.setText(person.getEmail());
        ssnTextField.setText(person.getNumeroSeguridadSocial());
        dobTextField.setText(person.getFechaNacimiento());
        geoTextField.setText(person.getPais());
        bankTextField.setText(person.getCuentaBancaria());
        phoneTextField.setText(person.getMovil());
        codeTextField.setText(String.valueOf(person.getCodEmpleado()));
        textFieldDepartment.setText(String.valueOf(person.getDepartamento()));
        fechaIncorptextField.setText(person.getFechaIncorp());
        sueldoTextField.setText(String.valueOf(person.getSueldo()));
        String imageTxt= person.getImagen();
       // imagePatTxt.setText(imageTxt);
        
        try {
            BufferedImage img = ImageIO.read(new File(imageTxt));

            imageLabel.setBounds(100, 100, 280, 250);

            Image dimg = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(),
                    Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(dimg);

            imageLabel.setIcon(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        dobTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bankTextField = new javax.swing.JTextField();
        ssnTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        geoTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        imageLabel.setBackground(new java.awt.Color(102, 102, 102));
        imageLabel.setOpaque(true);

        dobTextField.setEditable(false);

        jLabel2.setText("Nombre: ");

        jLabel3.setText("País: ");

        jLabel4.setText("Fecha de nacimiento: ");

        jLabel5.setText("Teléfono: ");

        jLabel7.setText("Email: ");

        jLabel8.setText("Número de SS: ");

        jLabel9.setText("Cuenta Bancaria: ");

        bankTextField.setEditable(false);

        ssnTextField.setEditable(false);

        emailTextField.setEditable(false);
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        phoneTextField.setEditable(false);

        geoTextField.setEditable(false);

        nameTextField.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Display Profile");
        
        codeTextField = new JTextField();
        codeTextField.setEditable(false);
        codeTextField.setColumns(10);
        
        JLabel jLabel10 = new JLabel("Código");
        
        textFieldDepartment = new JTextField();
        textFieldDepartment.setEditable(false);
        textFieldDepartment.setColumns(10);
        
        JLabel jLabel11 = new JLabel("Departamento");
        
        fechaIncorptextField = new JTextField();
        fechaIncorptextField.setEditable(false);
        fechaIncorptextField.setColumns(10);
        
        JLabel jLabel12 = new JLabel("Fecha Incorporación");
        
        jLabel13 = new JLabel("Sueldo");
        
        sueldoTextField = new JTextField();
        sueldoTextField.setEditable(false);
        sueldoTextField.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(64)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel8)
        								.addComponent(jLabel9)
        								.addComponent(jLabel11)
        								.addComponent(jLabel12)
        								.addComponent(jLabel13))
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(sueldoTextField)
        								.addComponent(bankTextField)
        								.addComponent(ssnTextField, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        								.addComponent(textFieldDepartment)
        								.addComponent(fechaIncorptextField)))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel3)
        							.addPreferredGap(ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
        							.addComponent(geoTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(jLabel5, Alignment.LEADING)
        								.addComponent(jLabel4, Alignment.LEADING))
        							.addGap(0, 244, Short.MAX_VALUE))
        						.addComponent(dobTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel2)
        							.addPreferredGap(ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
        							.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
        						.addComponent(phoneTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel7)
        								.addComponent(jLabel10))
        							.addPreferredGap(ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(codeTextField)
        									.addPreferredGap(ComponentPlacement.RELATED))
        								.addComponent(emailTextField, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap(251, Short.MAX_VALUE)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 212, GroupLayout.PREFERRED_SIZE)))
        			.addGap(69)
        			.addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 274, GroupLayout.PREFERRED_SIZE)
        			.addGap(260))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(74)
        			.addComponent(jLabel1)
        			.addGap(68)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel2)
        							.addGap(18)
        							.addComponent(jLabel3))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(geoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel4)
        						.addComponent(dobTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel5)
        						.addComponent(phoneTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(12)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(codeTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel10)
        							.addGap(18)
        							.addComponent(jLabel7)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel8)
        								.addComponent(ssnTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(jLabel9))
        						.addComponent(bankTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 238, GroupLayout.PREFERRED_SIZE)
        					.addGap(36)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textFieldDepartment, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel11))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(fechaIncorptextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel12))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel13)
        				.addComponent(sueldoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(119, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed


    // Variables deALLBITSclaration - do not modify//GEN-BEGIN:variables
     private  javax.swing.JTextField bankTextField;
     private javax.swing.JTextField dobTextField;
     private javax.swing.JTextField emailTextField;
     private javax.swing.JTextField geoTextField;
     private javax.swing.JLabel imageLabel;
      javax.swing.JLabel jLabel1;
      javax.swing.JLabel jLabel2;
      javax.swing.JLabel jLabel3;
      javax.swing.JLabel jLabel4;
      javax.swing.JLabel jLabel5;
      javax.swing.JLabel jLabel7;
      javax.swing.JLabel jLabel8;
      javax.swing.JLabel jLabel9;
      javax.swing.JLabel jLabel10;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField ssnTextField;
    private javax.swing.JTextField codeTextField;
    private javax.swing.JTextField textFieldDepartment;
    private JTextField fechaIncorptextField;
    private JLabel jLabel13;
    private JTextField sueldoTextField;
}
